### ISSUE TITLE
Delete Task List

### ISSUE THREAD

**Issue by killerkc12** [killerkc12/Taskboard#12]
Add 3 dots after the task list name.
on click of 3 dots should open menu pop(use the same pop-up menu used for the task) which will have a delete option.
after clicking on the delete option that list should be deleted as well all task from that list

**Comment by sdeepanshu17** [comment]
Please assign this issue to me.

**Comment by killerkc12** [comment]
sorry @sdeepanshu17 . This task is already done
I'll add more issue in coming day,

**Comment by killerkc12** [comment]
@sdeepanshu17 you can go a head
