### ISSUE TITLE
Centerize Add New Task List button

### ISSUE THREAD

**Issue by killerkc12** [killerkc12/Taskboard#17]
### Make this center align
![image](https://user-images.githubusercontent.com/50802786/193522499-32bf0655-ed11-427d-ac1d-77514e90c35f.png)

make sure tasklist name should not affected as we are using same CSS for both, So please make different CSS classes for this
![image](https://user-images.githubusercontent.com/50802786/193522948-1623e0d3-39fc-4131-bb49-8dd57fe28de7.png)

**Comment by Anurag-Singh-04** [comment]
Hey @killerkc12 could please explain what changes you want in this ?

**Comment by killerkc12** [comment]
There is a button named "+ Add new list". Make this button text to the center.

**Comment by Aryangp** [comment]
hi i can work on this issue you can assign it to me

**Comment by killerkc12** [comment]
@Aryangp, let @Anurag-Singh-04 respond first, is he interested or not?
If he said no then only I can assign it to you

**Comment by sayan404** [comment]
I would like to solve this issue ... please assign me this issue @killerkc12

**Comment by Aryangp** [comment]
Thanks

**Comment by Aryangp** [comment]
hi i am getting this error when npm start 
`Expected linebreaks to be 'LF' but found 'CRLF'`
can you tell how to solve

**Comment by killerkc12** [comment]
Footer of the VS contains CRLF
Please convert to LF
![image](https://user-images.githubusercontent.com/50802786/193639412-044e7ce1-02dd-45ec-b2e4-2f5e7aedd24e.png)

**Comment by Aryangp** [comment]
thanks it is solved
