### ISSUE TITLE
Delete tasks inside the tasklist

### ISSUE THREAD

**Issue by killerkc12** [killerkc12/Taskboard#20]
- When the user deletes a particular tasklist all the task under that tasklist stays as it is.
- While the user deletes the tasklist please delete all the tasks which are inside that tasklist

Required skill: React, Firebase 9

**Comment by yes-im-harsh** [comment]
I will try please assign it to me. @killerkc12

**Comment by Aryangp** [comment]
hi you just merged my pr #22  pls add hacktoberfest accepted tag in it otherwise it is not counting it pls its a request
